# Pandas Notebook

### Lists

In [100]:
#list ==> [<content>]
l = [1,2,3,4,"a", 7.4]
m = ["a","b","c","d"]
print(m,l)

['a', 'b', 'c', 'd'] [1, 2, 3, 4, 'a', 7.4]


### Dictionary

In [101]:
#dictionary ==> {"key" : "value"}
l_d = {"key1" : 1,
       "key2" : 2}
print(l_d)

{'key1': 1, 'key2': 2}


### Importing Pandas and Numpy libraries

In [66]:
import pandas as pd
import numpy as np

### Array

In [96]:
a = np.array([4,3,2])
a

array([4, 3, 2])

### Timestamp

In [82]:
pd.Timestamp('20130102')

Timestamp('2013-01-02 00:00:00')

### Series

In [97]:
pd.Series([1, 3, 5, np.nan, 6, 8])

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [98]:
pd.Series([1, 3, 5, np.nan, 6, "A"])

0      1
1      3
2      5
3    NaN
4      6
5      A
dtype: object

### Dates

In [58]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

## Pandas Dataframe

In [60]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [102]:
df2['E']

0     test
1    train
2     test
3    train
Name: E, dtype: category
Categories (2, object): [test, train]

In [103]:
df2['A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

#### creating a dataframe

In [21]:
dates = pd.date_range('20130101',periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [20]:
array = np.random.randn(6,4) #array with 6 rows and 4 columns
print(array)

[[-0.69854829 -0.89124013 -1.34611186  0.38814489]
 [-0.04150774  2.52360644  1.05893633  1.07351611]
 [ 0.67975097  1.48293636 -1.34507621 -0.05083829]
 [ 1.00138382  0.83296208 -0.88432435  0.8267838 ]
 [ 2.54181633  1.17791223  0.21069988  1.79948492]
 [-0.5354675  -0.46978024 -0.16364407 -0.77449408]]


###### https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

In [17]:
df = pd.DataFrame(array,index=dates,columns=list('1234'))

In [13]:
df

1         2         3         4
2013-01-01 -1.369864  0.344350 -0.465771  0.213300
2013-01-02  0.441857  0.752631  0.849010  1.180738
2013-01-03  0.287299 -0.197075 -0.067087 -2.576280
2013-01-04 -1.105887 -0.339436  0.233004 -0.104439
2013-01-05 -1.055670  0.053700  0.479815  0.013747
2013-01-06  0.056921  1.627299 -1.306816  0.260616

### changing title of dataframe

In [23]:
df = pd.DataFrame(array,index=dates,columns=["Jan","Feb", "March", "April"])
df

Jan       Feb     March     April
2013-01-01 -0.698548 -0.891240 -1.346112  0.388145
2013-01-02 -0.041508  2.523606  1.058936  1.073516
2013-01-03  0.679751  1.482936 -1.345076 -0.050838
2013-01-04  1.001384  0.832962 -0.884324  0.826784
2013-01-05  2.541816  1.177912  0.210700  1.799485
2013-01-06 -0.535467 -0.469780 -0.163644 -0.774494

In [9]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
np.random.randn(6,4)

array([[ 0.87523072,  1.22762361, -2.18004714,  0.09377348],
       [ 0.12643954,  1.52833159,  0.02425537,  0.5694043 ],
       [ 1.24902212, -0.58257937, -1.92326445,  0.78011686],
       [ 0.57586179, -0.43216375,  0.95601171,  1.41256557],
       [-0.12956763, -0.91985373,  1.18405106, -0.43693762],
       [-0.76625719,  0.38646942,  0.12718248,  1.74538985]])

In [54]:
df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })

In [55]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [56]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['column1', 'column2', 'column3'])

In [57]:
df

column1  column2  column3
mouse         1        2        3
rabbit        4        5        6

In [58]:
df.filter(items=['column1', 'column2'])

column1  column2
mouse         1        2
rabbit        4        5

In [59]:
x = df.filter(items=['column1', 'column2'])

In [60]:
x

column1  column2
mouse         1        2
rabbit        4        5

In [61]:
for i in x:
    print(x[i])

mouse     1
rabbit    4
Name: column1, dtype: int64
mouse     2
rabbit    5
Name: column2, dtype: int64


In [63]:
df

column1  column2  column3
mouse         1        2        3
rabbit        4        5        6

In [44]:
df * 2

column1  column2  column3
mouse         2        4        6
rabbit        8       10       12

In [64]:
df = df["column1"]*2

In [65]:
df

mouse     2
rabbit    8
Name: column1, dtype: int64

In [90]:
import pandas as pd
df = pd.read_excel(r'/home/philly/Downloads/K1 RECAP.xlsx', sheet_name="NY", header=3)
df.head()

Values  1231   Int     LTCG      Ord  Other Ded  20A - 201  \
0          Sum of H&AK  -1.8  0.64  10089.6   670.88   -1464.30      115.2   
1           Sum of BAO   0.0  0.16    420.4  -216.68       0.00        4.8   
2        Sum of HBK LT   0.0  0.40      0.0  -202.00       0.00        0.0   
3  Sum of KFK 92 Trust  -0.1  0.20      0.0  1262.90     -81.35        0.0   
4  Sum of MZK 92 Trust  -0.1  0.20      0.0  1262.90     -81.35        0.0   

   Grand Total  
0      9410.22  
1       208.68  
2      -201.60  
3      1181.65  
4      1181.65

In [95]:
df = pd.read_excel(r'/home/philly/Downloads/K1 RECAP.xlsx', sheet_name="MA", header=3)
df.head()

Values   Ord   WH  Grand Total
0          Sum of H&AK  34.2  1.8         36.0
1           Sum of BAO   0.0  0.0          0.0
2        Sum of HBK LT   0.0  0.0          0.0
3  Sum of KFK 92 Trust   1.9  0.1          2.0
4  Sum of MZK 92 Trust   1.9  0.1          2.0

In [128]:
df

Values   Ord   WH  Grand Total
0          Sum of H&AK  34.2  1.8         36.0
1           Sum of BAO   0.0  0.0          0.0
2        Sum of HBK LT   0.0  0.0          0.0
3  Sum of KFK 92 Trust   1.9  0.1          2.0
4  Sum of MZK 92 Trust   1.9  0.1          2.0
5            Sum of AJ   0.0  0.0          0.0
6   Sum of Summary Ptr  38.0  2.0         40.0

In [129]:
df['Values']

0            Sum of H&AK
1             Sum of BAO
2          Sum of HBK LT
3    Sum of KFK 92 Trust
4    Sum of MZK 92 Trust
5              Sum of AJ
6     Sum of Summary Ptr
Name: Values, dtype: object

In [130]:
df['Values'][4]

'Sum of MZK 92 Trust'

In [143]:
#value of ORD for condition df['Values'][4]
df['Ord'][4]

1.9000000000000001

In [161]:
if "Sum of MZK 92 Trust" in df["Values"]:
    print("yes")
else:
    print("no")

no


In [170]:
df.iloc[[1]]

Values  Ord   WH  Grand Total
1  Sum of BAO  0.0  0.0          0.0

In [171]:
df.iloc[[0, 1]]

Values   Ord   WH  Grand Total
0  Sum of H&AK  34.2  1.8         36.0
1   Sum of BAO   0.0  0.0          0.0

In [177]:
df.iloc[[0, 1, 3]]

Values   Ord   WH  Grand Total
0          Sum of H&AK  34.2  1.8         36.0
1           Sum of BAO   0.0  0.0          0.0
3  Sum of KFK 92 Trust   1.9  0.1          2.0

In [164]:
type(df['Values'])

pandas.core.series.Series

In [175]:
df['Values'].filter("Sum of MZK 92 Trust")

Series([], Name: Values, dtype: object)