### Importing Pandas and Numpy libraries

In [5]:
import pandas as pd
import numpy as np

#### creating a dataframe

In [21]:
dates = pd.date_range('20130101',periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [20]:
array = np.random.randn(6,4) #array with 6 rows and 4 columns
print(array)

[[-0.69854829 -0.89124013 -1.34611186  0.38814489]
 [-0.04150774  2.52360644  1.05893633  1.07351611]
 [ 0.67975097  1.48293636 -1.34507621 -0.05083829]
 [ 1.00138382  0.83296208 -0.88432435  0.8267838 ]
 [ 2.54181633  1.17791223  0.21069988  1.79948492]
 [-0.5354675  -0.46978024 -0.16364407 -0.77449408]]


###### https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

In [17]:
df = pd.DataFrame(array,index=dates,columns=list('1234'))

In [13]:
df

1         2         3         4
2013-01-01 -1.369864  0.344350 -0.465771  0.213300
2013-01-02  0.441857  0.752631  0.849010  1.180738
2013-01-03  0.287299 -0.197075 -0.067087 -2.576280
2013-01-04 -1.105887 -0.339436  0.233004 -0.104439
2013-01-05 -1.055670  0.053700  0.479815  0.013747
2013-01-06  0.056921  1.627299 -1.306816  0.260616

### changing title of dataframe

In [23]:
df = pd.DataFrame(array,index=dates,columns=["Jan","Feb", "March", "April"])
df

Jan       Feb     March     April
2013-01-01 -0.698548 -0.891240 -1.346112  0.388145
2013-01-02 -0.041508  2.523606  1.058936  1.073516
2013-01-03  0.679751  1.482936 -1.345076 -0.050838
2013-01-04  1.001384  0.832962 -0.884324  0.826784
2013-01-05  2.541816  1.177912  0.210700  1.799485
2013-01-06 -0.535467 -0.469780 -0.163644 -0.774494

In [9]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [11]:
np.random.randn(6,4)

array([[ 0.87523072,  1.22762361, -2.18004714,  0.09377348],
       [ 0.12643954,  1.52833159,  0.02425537,  0.5694043 ],
       [ 1.24902212, -0.58257937, -1.92326445,  0.78011686],
       [ 0.57586179, -0.43216375,  0.95601171,  1.41256557],
       [-0.12956763, -0.91985373,  1.18405106, -0.43693762],
       [-0.76625719,  0.38646942,  0.12718248,  1.74538985]])

In [14]:
df2 = pd.DataFrame({ 'A' : 1.,
                     'B' : pd.Timestamp('20130102'),
                     'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                     'D' : np.array([3] * 4,dtype='int32'),
                     'E' : pd.Categorical(["test","train","test","train"]),
                     'F' : 'foo' })

In [15]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [35]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['column1', 'column2', 'column3'])

In [36]:
df

column1  column2  column3
mouse         1        2        3
rabbit        4        5        6

In [38]:
df.filter(items=['column1', 'column2'])

column1  column2
mouse         1        2
rabbit        4        5

In [39]:
x = df.filter(items=['column1', 'column2'])

In [40]:
x

column1  column2
mouse         1        2
rabbit        4        5

In [41]:
for i in x:
    print(x[i])

mouse     1
rabbit    4
Name: column1, dtype: int64
mouse     2
rabbit    5
Name: column2, dtype: int64


In [42]:
for i in x:
    print(x[i])

mouse     1
rabbit    4
Name: column1, dtype: int64
mouse     2
rabbit    5
Name: column2, dtype: int64


In [43]:
df

column1  column2  column3
mouse         1        2        3
rabbit        4        5        6

In [44]:
df * 2

column1  column2  column3
mouse         2        4        6
rabbit        8       10       12

In [49]:
df = df["column1"]*2

In [50]:
df

mouse     2
rabbit    8
Name: column1, dtype: int64